### PR TITLE
DSE Spark Master locator

### PR DESCRIPTION
**Pull request by noorul**

### CODE REVIEW

**Comment by noorul** [comment]
@velvia Travis has not kicked in. Any why?

**Comment by velvia** [comment]
Probably because I haven’t enabled it in Travis yet  ;-)

**Comment by noorul** [comment]
@velvia How do I enable it?

**Comment by velvia** [comment]
Try going to Travis CI login and see if you can do it.  If not I can, but I think anybody who's collaborator on a repo can enable it. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Pull request closed without merging**
